name: Deploy Back

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd /polarag_backend
          git pull origin deploy
          echo "✅ Pulled latest source code."

      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v1

      - name: Verify uv installation
        run: uv --version

      - name: Install dependencies & Restart server
        run: |
          cd /polarag_backend
          uv sync
          pm2 reload backend
          echo "🚀 Backend server restarted."